network:
  version: 2
  ethernets:
    enp1s0f0np0:
      dhcp4: false
      addresses: 
        - 10.36.64.5/24
      nameservers:
        addresses:
          - 10.251.3.17
          - 10.249.10.13
      routes: 
        - via: 10.36.64.1
          to: default
